#!/usr/bin/env python3
"""Generate the architecture map and symbol index FROM the source.

Hand-drawn architecture diagrams drift the moment code changes. This reads the
Swift files, extracts every public symbol with its line, measures each file, and
infers cross-file edges from actual symbol usage — so the picture in the README
is a fact about the repo rather than a claim about it.

    python3 Scripts/mkmap.py        # writes assets/map.svg + docs/ARCHITECTURE.md
"""
import re, os, json, pathlib, subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC  = sorted((ROOT / "Sources").rglob("*.swift")) + sorted((ROOT / "Tests").rglob("*.swift"))

DECL = re.compile(r'^\s*(?:public\s+|)(?P<kw>enum|struct|final class|class|protocol|extension)\s+(?P<name>\w+)')
FUNC = re.compile(r'^\s*(?:public\s+|)(?:static\s+)?func\s+(?P<name>\w+)')
PROP = re.compile(r'^\s*public\s+(?:static\s+)?(?:let|var)\s+(?P<name>\w+)')
PUB  = re.compile(r'^\s*public\s+')

ROLE = {
    "RPR.swift":     ("periodicity core", "#58A6FF"),
    "PGVR.swift":    ("the loop", "#BC8CFF"),
    "Ollama.swift":  ("model transport", "#3FB950"),
    "Loupe.swift":   ("public facade", "#D29922"),
    "main.swift":    ("command line", "#FF7B72"),
    "RPRTests.swift":("validation gate", "#8B949E"),
}

files = []
for p in SRC:
    lines = p.read_text().splitlines()
    syms, doc = [], ""
    for i, l in enumerate(lines, 1):
        if not doc and l.strip().startswith("///"):
            doc = l.strip().lstrip("/ ").strip()
        m = DECL.match(l) or FUNC.match(l) or PROP.match(l)
        if m:
            kind = m.groupdict().get("kw", "func" if FUNC.match(l) else "prop")
            syms.append(dict(name=m.group("name"), line=i, kind=kind,
                             public=bool(PUB.match(l))))
    role, colour = ROLE.get(p.name, ("", "#8B949E"))
    files.append(dict(path=str(p.relative_to(ROOT)), name=p.name, loc=len(lines),
                      syms=syms, role=role, colour=colour, doc=doc,
                      code=sum(1 for l in lines if l.strip() and not l.strip().startswith("//"))))

# cross-file edges: a file that mentions another's top-level type depends on it
tops = {f["name"]: {s["name"] for s in f["syms"] if s["kind"] in
                    ("enum","struct","final class","class","protocol")} for f in files}
edges = set()
for f in files:
    body = (ROOT / f["path"]).read_text()
    for g in files:
        if g is f: continue
        for t in tops[g["name"]]:
            if re.search(rf'\b{t}\b', body):
                edges.add((f["name"], g["name"])); break

# ── ARCHITECTURE.md ──────────────────────────────────────────────────────────
md = ["# Architecture", "",
      "> Generated by `Scripts/mkmap.py` from the source. Do not edit by hand — "
      "run the script instead, and it will always match the code.", "",
      '<p align="center"><img src="../assets/map.svg" alt="module map" width="100%"></p>', "",
      "## Files", "",
      "| file | role | lines | public symbols |", "|---|---|---:|---:|"]
for f in files:
    pubs = sum(1 for s in f["syms"] if s["public"])
    md.append(f'| [`{f["path"]}`]({"../" + f["path"]}) | {f["role"]} | {f["loc"]} | {pubs} |')
md += ["", f'**Total — {sum(f["loc"] for f in files)} lines across {len(files)} files, '
           f'{sum(f["code"] for f in files)} of them code.**', "", "## Public API", ""]
for f in files:
    pubs = [s for s in f["syms"] if s["public"]]
    if not pubs: continue
    md.append(f'### `{f["name"]}` — {f["role"]}')
    if f["doc"]: md.append(f'*{f["doc"]}*')
    md.append("")
    for s in pubs:
        md.append(f'- `{s["name"]}` <sub>{s["kind"]} · '
                  f'[L{s["line"]}]({"../" + f["path"]}#L{s["line"]})</sub>')
    md.append("")
md += ["## Dependencies", "", "```"]
for a, b in sorted(edges):
    md.append(f"{a:16s} → {b}")
md += ["```", ""]
(ROOT / "docs" / "ARCHITECTURE.md").write_text("\n".join(md))

# ── map.svg ──────────────────────────────────────────────────────────────────
BG="#0B0F14"; PANEL="#111820"; EDGE="#1E2A38"; TXT="#E6EDF3"; MUT="#8B949E"; DIM="#6E7A87"
FONT="-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif"
MONO="ui-monospace,SFMono-Regular,Menlo,monospace"
order = ["RPR.swift","PGVR.swift","Ollama.swift","Loupe.swift","main.swift","RPRTests.swift"]
files.sort(key=lambda f: order.index(f["name"]) if f["name"] in order else 99)

W = 1200
COLS, CW, GAP, X0, Y0 = 3, 360, 30, 44, 108
maxloc = max(f["loc"] for f in files)
body, pos = "", {}
for i, f in enumerate(files):
    c, r = i % COLS, i // COLS
    x = X0 + c*(CW+GAP); y = Y0 + r*236
    pos[f["name"]] = (x + CW/2, y)
    # A card with no public symbols would render blank; show what is there.
    pubs = ([s for s in f["syms"] if s["public"]] or f["syms"])[:7]
    body += f'<rect x="{x}" y="{y}" width="{CW}" height="212" rx="12" fill="{PANEL}" stroke="{EDGE}"/>'
    body += f'<rect x="{x}" y="{y}" width="{CW}" height="3" rx="1.5" fill="{f["colour"]}"/>'
    body += (f'<text x="{x+18}" y="{y+32}" font-size="15" font-weight="600" fill="{TXT}" '
             f'font-family="{MONO}">{f["name"]}</text>')
    body += (f'<text x="{x+CW-18}" y="{y+32}" font-size="11" fill="{DIM}" text-anchor="end" '
             f'font-family="{MONO}">{f["loc"]} lines</text>')
    body += f'<text x="{x+18}" y="{y+52}" font-size="11.5" fill="{f["colour"]}">{f["role"]}</text>'
    # LOC bar
    bw = (CW-36) * f["loc"] / maxloc
    body += f'<rect x="{x+18}" y="{y+62}" width="{CW-36}" height="3" rx="1.5" fill="#1A2430"/>'
    body += f'<rect x="{x+18}" y="{y+62}" width="{bw:.0f}" height="3" rx="1.5" fill="{f["colour"]}" opacity="0.7"/>'
    if not pubs:
        # Top-level code (an entry point) declares nothing; say what it is.
        for j, l in enumerate([f["doc"] or "top-level entry point", "reads stdin → writes stdout"]):
            body += (f'<text x="{x+18}" y="{y+90+j*17}" font-size="11" fill="{MUT}">{l[:44]}</text>')
    for j, s in enumerate(pubs):
        body += (f'<text x="{x+18}" y="{y+88+j*17}" font-size="11" fill="{MUT}" '
                 f'font-family="{MONO}">{s["name"]}</text>')
        body += (f'<text x="{x+CW-18}" y="{y+88+j*17}" font-size="10" fill="#4A5560" '
                 f'text-anchor="end" font-family="{MONO}">L{s["line"]}</text>')
    extra = len([s for s in f["syms"] if s["public"]] or f["syms"]) - len(pubs)
    if extra > 0:
        body += (f'<text x="{x+18}" y="{y+88+len(pubs)*17}" font-size="10.5" fill="{DIM}">'
                 f'+{extra} more</text>')
H = Y0 + ((len(files)+COLS-1)//COLS)*236 + 40
head = (f'<text x="44" y="44" font-size="17" font-weight="600" fill="{TXT}">What is actually built</text>'
        f'<text x="44" y="66" font-size="12.5" fill="{MUT}">'
        f'{sum(f["loc"] for f in files)} lines across {len(files)} files. '
        f'Generated from the source by Scripts/mkmap.py, so it cannot drift.</text>')
svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" '
       f'font-family="{FONT}"><rect width="{W}" height="{H}" rx="16" fill="{BG}"/>{head}{body}</svg>')
(ROOT / "assets" / "map.svg").write_text(svg)
print(f"map.svg  {W}x{H}   ARCHITECTURE.md  {len(files)} files, "
      f"{sum(len(f['syms']) for f in files)} symbols, {len(edges)} edges")
